"use client";
import { useEffect, useRef, useState } from 'react';
import { ArrowUpRight, ArrowRight, Check, Plus, Minus, Eye, MousePointer2, Maximize2, Layers, Navigation, Aperture, Command, X } from 'lucide-react';
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs';

const details=[{name:'The frame',label:'A familiar silhouette. An unfamiliar possibility.',text:'A sculpted graphite form that belongs in your day. Technology integrated into eyewear, with every line serving a purpose.',x:49,y:57},{name:'The optics',label:'Your world, with another dimension.',text:'Transparent lenses keep the real world in view. Digital information finds its place alongside it.',x:32,y:65},{name:'The temple',label:'Everything considered. Nothing announced.',text:'A quiet profile brings the computing experience together. Concealed within the familiar architecture of a pair of glasses.',x:76,y:40}];
export default function Home(){
 const [email,setEmail]=useState('');const [status,setStatus]=useState<'idle'|'loading'|'success'|'error'>('idle');const [message,setMessage]=useState('');
 const [mode,setMode]=useState('create');const [ar,setAr]=useState(true);const [detail,setDetail]=useState(0);const [expanded,setExpanded]=useState(false);const [seconds,setSeconds]=useState(0);const [focusRunning,setFocusRunning]=useState(false);
 const journey=useRef<HTMLElement>(null);const scene=useRef<HTMLDivElement>(null);const product=useRef<HTMLDivElement>(null);
 useEffect(()=>{let frame=0;const reduced=matchMedia('(prefers-reduced-motion: reduce)');const update=()=>{frame=0;if(!journey.current)return;const rect=journey.current.getBoundingClientRect();const p=Math.max(0,Math.min(1,-rect.top/(rect.height-innerHeight)));journey.current.style.setProperty('--p',String(reduced.matches?0:p));journey.current.style.setProperty('--intro',String(Math.max(0,1-p*3)));journey.current.style.setProperty('--outro',String(Math.max(0,Math.min(1,(p-.5)*3))));document.documentElement.style.setProperty('--scroll',String(scrollY/(document.documentElement.scrollHeight-innerHeight)))};const scroll=()=>{if(!frame)frame=requestAnimationFrame(update)};window.addEventListener('scroll',scroll,{passive:true});window.addEventListener('resize',scroll);update();const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.12});document.querySelectorAll('.reveal').forEach(e=>observer.observe(e));return()=>{cancelAnimationFrame(frame);window.removeEventListener('scroll',scroll);window.removeEventListener('resize',scroll);observer.disconnect()}},[]);
 useEffect(()=>{if(!focusRunning)return;const t=setInterval(()=>setSeconds(s=>s+1),1000);return()=>clearInterval(t)},[focusRunning]);
 useEffect(()=>{if(!expanded)return;const before=document.body.style.overflow;document.body.style.overflow='hidden';const close=(e:KeyboardEvent)=>{if(e.key==='Escape'){setExpanded(false);requestAnimationFrame(()=>document.getElementById('expand-view')?.focus())}if(e.key==='Tab'){const items=Array.from(scene.current?.querySelectorAll<HTMLElement>('button:not(:disabled), [tabindex="0"]')||[]).filter(el=>el.getClientRects().length>0&&getComputedStyle(el).visibility!=='hidden');const first=items[0],last=items[items.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}};window.addEventListener('keydown',close);document.getElementById('close-view')?.focus();return()=>{document.body.style.overflow=before;window.removeEventListener('keydown',close)}},[expanded]);
 function move(e:React.PointerEvent<HTMLDivElement>,ref:React.RefObject<HTMLDivElement|null>){if(e.pointerType==='touch'||matchMedia('(prefers-reduced-motion: reduce)').matches)return;const r=e.currentTarget.getBoundingClientRect();ref.current?.style.setProperty('--mx',String((e.clientX-r.left)/r.width-.5));ref.current?.style.setProperty('--my',String((e.clientY-r.top)/r.height-.5))}
 function reset(ref:React.RefObject<HTMLDivElement|null>){ref.current?.style.setProperty('--mx','0');ref.current?.style.setProperty('--my','0')}
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setStatus('loading');try{const r=await fetch('/api/waitlist',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email})});const data=await r.json() as {error?:string};if(!r.ok)throw new Error(data.error||'Please try again.');setStatus('success')}catch(e){setStatus('error');setMessage(e instanceof Error?e.message:'Something went wrong. Please try again.')}}
 return <><a className="skip" href="#experience">Skip to experience</a><div className="read-progress"/>
 <header className="navigation"><a className="wordmark" href="#" aria-label="BLANK home">BLANK<span>®</span></a><a className="nav-product" href="#design">BLANK 1O <span>— FIRST EDITION</span></a><a href="#waitlist" className="nav-cta">Get early access <ArrowUpRight size={16}/></a></header>
 <main>
 <section className="journey" ref={journey} aria-labelledby="hero-title"><div className="journey-sticky"><div className="intro"><div className="hero-meta"><span className="eyebrow"><i/> A NEW PERSPECTIVE ON COMPUTING</span><span className="edition">ENGINEERED FOR THE WORLD AHEAD.</span></div><h1 id="hero-title">Beyond<span>the screen.</span></h1><div className="hero-sub"><span>Introducing BLANK 1O.</span><p>Your world. Infinitely more possible.</p></div></div><div className="hero-object" ref={product} onPointerMove={e=>move(e,product)} onPointerLeave={()=>reset(product)}><div className="object-inner"><img src="/blank-1o.png" alt="Sculpted graphite BLANK 1O augmented reality glasses" fetchPriority="high"/><div className="object-tag"><span className="tag-line"/>BLANK 1O / GRAPHITE</div></div></div><div className="outro"><span className="eyebrow">THE NEXT INTERFACE IS NO INTERFACE.</span><h2>Look up.<br/><em>Open everything.</em></h2><p>Less between you and your ideas.<br/>More of the world in front of you.</p><a className="pill black" href="#experience">Step inside the experience <ArrowUpRight size={18}/></a></div><div className="hero-floor"><a href="#experience"><span className="scroll-orbit">↓</span> SCROLL TO SEE BEYOND</a><span>PROFESSIONAL AR EYEWEAR</span><span className="chapter">01 <span>/</span> 03</span></div></div></section>
 <section className="experience" id="experience"><div className="experience-intro reveal"><div className="section-index">01 — A DIFFERENT POINT OF VIEW</div><div className="split-heading"><h2>Reality.<br/><em>With possibility.</em></h2><div><p>Don’t imagine the difference.<br/>See through it.</p><span className="small">AN INTERACTIVE BLANK OS CONCEPT</span></div></div></div>
 <div className={'lens-demo '+(expanded?'expanded':'')} role={expanded?'dialog':undefined} aria-modal={expanded||undefined} aria-label={expanded?'BLANK OS interactive experience':undefined} ref={scene} onPointerMove={e=>move(e,scene)} onPointerLeave={()=>reset(scene)}><img className="world" src="/studio.png" alt="A quiet coastal design studio looking out onto the ocean"/><div className="world-shade"/><div className="view-top"><span className="view-brand">B<span>/</span></span><span className="view-time">YOUR WORLD, STILL IN VIEW.</span><button id={expanded?'close-view':'expand-view'} onClick={()=>setExpanded(!expanded)} aria-label={expanded?'Close expanded view':'Expand experience'}>{expanded?<X size={20}/>:<Maximize2 size={18}/>}</button></div>
 <div className={'ar-layer '+(!ar?'off':'')} aria-hidden={!ar}><div className="side-widget"><span className="widget-icon"><Aperture size={19}/></span><div>Good afternoon.<small>Make room for a new idea.</small></div></div><div className={'spatial-window '+mode} key={mode}><div className="window-bar"><span><i/> {mode==='create'?'STUDIO / UNTITLED 01':mode==='focus'?'FOCUS / YOUR SPACE':'EXPLORE / THE COAST'}</span><Layers size={15}/></div>{mode==='create'?<div className="workspace"><div className="workspace-label">A SPACE FOR YOUR NEXT IDEA</div><h3>Good things start<br/>with a blank.</h3><div className="creative-orbit" aria-hidden="true"><span/><span/><span/><div>01</div></div><div className="workspace-foot"><span>Perspective study</span><span>↗</span></div></div>:mode==='focus'?<div className="focus-space"><span className="workspace-label">ONE THING AT A TIME.</span><div className="timer">{String(Math.floor(seconds/60)).padStart(2,'0')}<span>:</span>{String(seconds%60).padStart(2,'0')}</div><p>Your attention is your superpower.</p><button disabled={!ar} onClick={()=>setFocusRunning(!focusRunning)}>{focusRunning?'Pause session':seconds?'Resume focus':'Begin focus'} {focusRunning?<Minus size={14}/>:<ArrowRight size={14}/>}</button></div>:<div className="explore-space"><Navigation size={32}/><span className="workspace-label">A LITTLE FURTHER. A LITTLE FREER.</span><h3>Take the<br/>scenic route.</h3><div className="route-line"><i/><span/><i/></div><p>Coastal path <span>12 min walk</span></p></div>}</div><div className="mini-widget"><span className="tiny">IN YOUR ELEMENT</span><strong>{mode==='create'?'Room to create.':mode==='focus'?'Space to focus.':'Freedom to explore.'}</strong><span className="mini-rule"/><span>Less distraction.<br/>More possibility.</span></div><div className="reticle" aria-hidden="true">+</div></div>
 <div className="demo-bottom"><div className="demo-modes"><Tabs value={mode} onValueChange={setMode}><TabsList><TabsTrigger value="create"><Command size={14}/> Create</TabsTrigger><TabsTrigger value="focus"><Aperture size={14}/> Focus</TabsTrigger><TabsTrigger value="explore"><Navigation size={14}/> Explore</TabsTrigger></TabsList></Tabs></div><button className="ar-toggle" aria-pressed={ar} onClick={()=>setAr(!ar)}><Eye size={16}/><span>Digital layer</span><span className={'toggle '+(ar?'on':'')}><i/></span></button></div></div><div className="demo-caption"><span><MousePointer2 size={13}/> MOVE TO LOOK AROUND · SELECT A MODE TO EXPLORE</span><span>ILLUSTRATIVE EXPERIENCE / NOT FINAL PRODUCT UI</span></div>
 </section>
 <section className="manifesto"><span className="section-index reveal">COMPUTING SHOULD OPEN YOUR WORLD.</span><p className="reveal">Not take you<br/><span>out of it.</span></p><span className="manifesto-foot reveal">BUILT AROUND LIFE. NOT THE OTHER WAY AROUND.</span></section>
 <section className="design" id="design"><div className="design-top reveal"><span className="section-index">02 — NOTHING WITHOUT INTENTION</span><h2>Technology.<br/><em>In its quietest form.</em></h2></div><div className="inspection"><div className="inspection-image"><img src="/blank-1o.png" alt="Explore the frame, lenses, and temples of BLANK 1O" loading="lazy"/>{details.map((d,i)=><button className={'hotspot '+(detail===i?'selected':'')} key={d.name} style={{left:d.x+'%',top:d.y+'%'}} onClick={()=>setDetail(i)} aria-label={'Inspect '+d.name} aria-pressed={detail===i}>{detail===i?<Minus size={14}/>:<Plus size={14}/>}</button>)}<span className="inspect-instruction">SELECT A DETAIL. GET CLOSER.</span></div><div className="inspection-info"><div className="detail-nav">{details.map((d,i)=><button key={d.name} onClick={()=>setDetail(i)} aria-pressed={detail===i} className={detail===i?'active':''}><span>0{i+1}</span>{d.name}</button>)}</div><div className="detail-story" key={detail} aria-live="polite"><span className="section-index">BLANK 1O / 0{detail+1}</span><h3>{details[detail].label}</h3><p>{details[detail].text}</p></div><span className="material-swatch"><i/> GRAPHITE / FIRST EDITION</span></div></div></section>
 <section className="waitlist" id="waitlist"><div className="section-label"><span>03 / AN INVITATION TO WHAT’S NEXT</span><span>EARLY ACCESS</span></div><div className="waitlist-body"><div><span className="eyebrow">THE NEXT CHAPTER STARTS WITH YOU.</span><h2>Be there at the beginning.</h2><p>Be part of a new perspective.<br/>Explore the BLANK 1O concept and try the waitlist experience.</p></div><div className="form-wrap">{status==='success'?<div className="success" role="status"><Check size={28}/><h3>You’re on the list.</h3><p>Your signup has been saved for this concept demonstration.</p><span>{email}</span></div>:<form onSubmit={submit}><label htmlFor="email">Your email address</label><div className="input-row"><input id="email" name="email" type="email" autoComplete="email" required maxLength={254} placeholder="you@example.com" value={email} onChange={e=>setEmail(e.target.value)} disabled={status==='loading'}/><button aria-label="Join the BLANK 1O waitlist" disabled={status==='loading'} type="submit">{status==='loading'?'Joining…':<ArrowUpRight size={28}/>}</button></div><p className="consent">BLANK is a fictional product concept.<br/>This demo stores your email; no launch emails are sent.</p>{status==='error'&&<p className="error" role="alert">{message}</p>}<button className="form-submit" disabled={status==='loading'} type="submit">{status==='loading'?'Joining the waitlist…':'Join the waitlist'} <ArrowRight size={16}/></button></form>}</div></div><div className="bottom-wordmark" aria-hidden="true">BLANK<span>®</span></div></section>
 </main><footer><span>© {new Date().getFullYear()} BLANK</span><span>A NEW FRAME OF MIND.</span><span>FICTIONAL PRODUCT CONCEPT</span><a href="#">Back to top ↑</a></footer>
 </>;
}
